### ISSUE TITLE
Uncaught Error: "barWithErrorBars" is not a registered controller (v3.9.1)

### ISSUE THREAD

**Issue by AlonMiz** [sgratzl/chartjs-chart-error-bars#29]
When I import the plugin while using this with react-chartjs-2 i get the error below

```
Uncaught Error: "barWithErrorBars" is not a registered controller.
    at Registry._get (chart.esm.js:4916:13)
    at Registry.getController (chart.esm.js:4862:17)
    at Chart.buildOrUpdateControllers (chart.esm.js:5610:42)
    at Chart.update (chart.esm.js:5644:33)
    at new Chart (chart.esm.js:5426:12)
    at renderChart (chart.tsx:42:24)
    at chart.tsx:98:5
    at invokePassiveEffectCreate (react-dom.development.js:23487:20)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:16)
```
looking through the getController function i see that these are registered:
```
pointWithErrorBar plugin
barWithErrorBars plugin
barWithErrorBar plugin
pointWithErrorBar plugin
barWithErrorBars plugin
barWithErrorBar plugin
pointWithErrorBar plugin
barWithErrorBars plugin
barWithErrorBar plugin
barWithErrorBars controller throws
```
**To Reproduce**

that's a rough code (not complete, but the essentials are here)
```tsx
import { ChartData, ChartOptions, Point, Chart as ChartJS, BarControllerChartOptions } from 'chart.js';
import {
  BarWithErrorBar,
  BarWithErrorBarsController,
  PointWithErrorBar,
  BarWithErrorBarsChart,
} from 'chartjs-chart-error-bars';

// these all registers i tries to add
ChartJS.register(
  PointWithErrorBar,
  BarWithErrorBarsController,
  BarWithErrorBar,
  BarWithErrorBarsChart,
  LinearScale,
  CategoryScale,
  BarElement,
  LinearScale,
  PointElement,
  LineElement,
  TimeScale,
  CategoryScale,
  Title,
  Tooltip,
  Legend,
  Decimation,
  Tooltip,
  Legend,
  annotationPlugin
);

const options = {
            annotations,
            scales: {
              x: {
                type: 'time',
                ticks: {
                  source: 'auto',
                },
              },
              y: {
                suggestedMin: 0,
              },
            },
          };

const getChartDatasets = (data:IErrorBarXYDataPoint[]): ChartData<'barWithErrorBars'> => ({
  labels: data.map(({ x }) => x),
  datasets: [
    {
      data,
    },
  ],
});


const BarChartWithErrors = () => {
return <Chart
        type="barWithErrorBars"
        data={chartDatasets}
        options={chartOptions}
        plugins={[chartUtils.backgroundPlugin]}
      />
}
```
**Expected behavior**
after registering BarWithErrorBarsController i expect it to not throw saying it's not registered

**Screenshots**
<img width="907" alt="image" src="https://user-images.githubusercontent.com/1812912/184807598-62be5007-7cb2-46f8-985e-a2ea1a0d0a9f.png">

**Context**

- Version: latest
- Browser: chrome latest
```
    "chart.js": "3.9.1",
    "chartjs-adapter-dayjs-3": "1.2.3",
    "chartjs-chart-error-bars": "3.9.0",
    "chartjs-plugin-annotation": "1.4.0",
    "react-chartjs-2": "4.3.1",
```

**Comment by sgratzl** [comment]
can you create a codesandbox, codepen, ... where I can reproduce the error?

**Comment by njdavis** [comment]
If I have time later tonight, I'll try to create a codepen. I just wanted to say that this bug is showing up for me as well, whenever I use 3.9.0. It seems to work fine for 3.8.0, and below.

**Comment by AlonMiz** [comment]
it does work on version 3.8.0

**Comment by sgratzl** [comment]
one code change I can think of is https://github.com/sgratzl/chartjs-chart-error-bars/commit/e2aae8a9ee6d0967c3d6b60775037edb0b7e90a7#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519 which removes the "browser" field from th the package.json but I don't know how that could effect things.

**Comment by sgratzl** [comment]
this works just fine for me:

```jsx
import { Chart as ChartJS, Title, Tooltip, LinearScale, CategoryScale, BarElement } from 'chart.js';
import {
    BarWithErrorBar,
    BarWithErrorBarsController,
    PointWithErrorBar,
} from 'chartjs-chart-error-bars';
import { Chart } from 'react-chartjs-2';

// these all registers i tries to add
ChartJS.register(
    PointWithErrorBar,
    BarWithErrorBarsController,
    BarWithErrorBar,
    LinearScale,
    CategoryScale,
    BarElement,
    LinearScale,
    CategoryScale,
    Title,
    Tooltip,
);

const options = {
    // annotations,
    scales: {
        x: {
            // type: 'time',
            // ticks: {
            //     source: 'auto',
            // },
        },
        y: {
            suggestedMin: 0,
        },
    },
};

const getChartDatasets = (data) => ({
    labels: data.map(({ x }) => x),
    datasets: [
        {
            data,
        },
    ],
});


export const BarChartWithErrors = () => {
    return <Chart
        type="barWithErrorBars"
        data={getChartDatasets([{ x: 'a', y: 3, yMin: 1, yMax: 4 }, { x: 'b', y: 2 }, { x: 'c', y: 1 }])}
        width={300}
        height={200}
        options={options}
    />
}
```

"chartjs-chart-error-bars": "^3.10.0",
    "chart.js": "^3.9.1",
    "react-chartjs-2": "^4.3.1",
